version: "3"

services:
  whisper-api:
    container_name: whisper-api
    build:
      context: .
      dockerfile: Dockerfile.gpu
    runtime: nvidia
    ports:
      - "8088:8000"
    env_file:
      - .env
   
